<?php

 /*********************************************************************************
  * The contents of this file are subject to the SugarCRM Professional End User
  * License Agreement ('License') which can be viewed at
  * http://www.sugarcrm.com/crm/products/sugar-professional-eula.html
  * By installing or using this file, You have unconditionally agreed to the
  * terms and conditions of the License, and You may not use this file except in
  * compliance with the License.  Under the terms of the license, You shall not,
  * among other things: 1) sublicense, resell, rent, lease, redistribute, assign
  * or otherwise transfer Your rights to the Software, and 2) use the Software
  * for timesharing or service bureau purposes such as hosting the Software for
  * commercial gain and/or for the benefit of a third party.  Use of the Software
  * may be subject to applicable fees and any use of the Software without first
  * paying applicable fees is strictly prohibited.  You do not have the right to
  * remove SugarCRM copyrights from the source code or user interface.
  * All copies of the Covered Code must include on each user interface screen:
  * (i) the 'Powered by SugarCRM' logo and
  * (ii) the SugarCRM copyright notice
  * in the same form as they appear in the distribution.  See full license for
  * requirements.
  * Your Warranty, Limitations of liability and Indemnity are expressly stated
  * in the License.  Please refer to the License for the specific language
  * governing these rights and limitations under the License.  Portions created
  * by SugarCRM are Copyright (C) 2004-2005 SugarCRM, Inc.; All Rights Reserved.
  ********************************************************************************/
  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/Machines/language/us_us.lang.php,  Thu 01/03/07 16:23:40 
  * Description : .
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s): 
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'ERR_DELETE_RECORD' => 'A record number must be specified to delete the account.' ,
   
   'LBL_ACCOUNT_ID' => 'Account ID' ,
   'LBL_ACCOUNT_NAME' => 'Account Name:' ,
   'LBL_ACTIVITIES_SUBPANEL_TITLE' => 'Activities' ,
   'LBL_BUGS_SUBPANEL_TITLE' => 'Bugs' ,
   'LBL_MACHINE_NUMBER' => 'Machine Number:' ,
   'LBL_MACHINE_SUBJECT' => 'Machine Subject:' ,
   'LBL_MACHINE' => 'Machine:' ,
   'LBL_CONTACT_MACHINE_TITLE' => 'Contact-Machine:' ,
   'LBL_CONTACT_NAME' => 'Contact Name:' ,
   'LBL_CONTACT_ROLE' => 'Role:' ,
   'LBL_CONTACTS_SUBPANEL_TITLE' => 'Contacts' ,
   'LBL_DEFAULT_SUBPANEL_TITLE' => 'Machines' ,
   'LBL_DESCRIPTION' => 'Description:' ,
   'LBL_HISTORY_SUBPANEL_TITLE' => 'History' ,
   'LBL_INVITEE' => 'Contacts' ,
   'LBL_MEMBER_OF' => 'Account' ,
   'LBL_MODULE_NAME' => 'Machines' ,
   'LBL_MODULE_TITLE' => 'Machines: Home' ,
   'LBL_NEW_FORM_TITLE' => 'New Machine' ,
   'LBL_FORMAT' => 'Format:' ,
   'LBL_SEARCH_FORM_TITLE' => 'Machine Search' ,
   'LBL_CATEGORY' => 'Category:' ,
   'LBL_SUBJECT' => 'Name:' ,
   'LBL_SYSTEM_ID' => 'System ID' ,
   
   'LBL_LIST_ACCOUNT_NAME' => 'Account Name' ,
   'LBL_LIST_ASSIGNED' => 'Assigned To' ,
   'LBL_LIST_CLOSE' => 'Close' ,
   'LBL_LIST_FORM_TITLE' => 'Machine List' ,
   'LBL_LIST_LAST_MODIFIED' => 'Last Modified' ,
   'LBL_LIST_MY_MACHINES' => 'My Open Machines' ,
   'LBL_LIST_NUMBER' => 'Num.' ,
   'LBL_LIST_PRIORITY' => 'Priority' ,
   'LBL_LIST_STATUS' => 'Status' ,
   'LBL_LIST_SUBJECT' => 'Subject' ,
   
   'LNK_MACHINE_LIST' => 'Machines' ,
   'LNK_NEW_MACHINE' => 'Create Machine' ,
   'NTC_REMOVE_FROM_BUG_CONFIRMATION' => 'Are you sure you want to remove this machine from this bug?' ,
   'NTC_REMOVE_INVITEE' => 'Are you sure you want to remove this contact from the machine?' ,
   'LBL_LIST_ASSIGNED_TO_NAME' => 'Assigned User' ,
   'LBL_LIST_DATE_CREATED' => 'Date Created' 
);
?>
